name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v11
    - name: Run
      env:
        SCALANATIVE_MODE: release-fast
      run: sbt run